### ISSUE TITLE
Exception using german voice and "ch" sound

### ISSUE THREAD

**Issue by undernorthernsky** [rhasspy/piper#104]
```
$ echo "manchmal" | ./piper -m de-thorsten-low.onnx -f test.wav
[2023-06-11 04:06:55.570] [piper] [info] Loaded voice in 0.396094405 second(s)
[2023-06-11 04:06:55.571] [piper] [info] Initialized piper
2023-06-11 04:06:55.576160841 [E:onnxruntime:, sequential_executor.cc:494 ExecuteKernel] Non-zero status code returned while running Gather node. Name:'/enc_p/emb/Gather' Status Message: indices element out of data bounds, idx=140 must be within the inclusive range [-130,129]
terminate called after throwing an instance of 'Ort::Exception'
  what():  Non-zero status code returned while running Gather node. Name:'/enc_p/emb/Gather' Status Message: indices element out of data bounds, idx=140 must be within the inclusive range [-130,129]
Aborted
```
same error for "ich", "wichtig", …

stacktrace:
```
#7  0x00005555555ae76a in Ort::ThrowOnError (ort_status=<optimized out>)
    at ../../onnxruntime-linux-x64-1.14.1/include/onnxruntime_cxx_inline.h:23
#8  0x00005555555aaa47 in Ort::detail::SessionImpl<OrtSession>::Run (this=0x7fffffffd878, this=0x7fffffffd878, 
    output_count=1, output_values=0x555555c90c30, output_names=0x7fffffffcd10, input_count=3, input_values=0x5555565ec230, 
    input_names=0x7fffffffce80, run_options=...) at ../../onnxruntime-linux-x64-1.14.1/include/onnxruntime_cxx_inline.h:895
#9  Ort::detail::SessionImpl<OrtSession>::Run (output_count=1, output_names=0x7fffffffcd10, input_count=<optimized out>, 
    input_values=<optimized out>, input_names=0x7fffffffce80, run_options=..., this=0x7fffffffd878)
    at ../../onnxruntime-linux-x64-1.14.1/include/onnxruntime_cxx_inline.h:885
#10 piper::synthesize (phonemeIds=..., synthesisConfig=..., session=..., audioBuffer=..., result=...) at piper.cpp:314
#11 0x00005555555ac01e in piper::textToAudio(piper::PiperConfig&, piper::Voice&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<short, std::allocator<short> >&, piper::SynthesisResult&, std::function<void ()> const&) (config=..., voice=..., text=..., audioBuffer=..., result=..., audioCallback=...) at piper.cpp:456
#12 0x00005555555ad5df in piper::textToWavFile (config=..., voice=..., text=" manchmal", audioFile=..., result=...)
    at piper.cpp:501
#13 0x000055555556ac19 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:221
```

Note: main.cpp slightly modified; I wanted an option to load a multi line string from a file and generate a single wav.
Compiled against latest rhasspy/espeak-ng & rhasspy/piper-phonemize but build in a haphazard way.
Otherwise seems to work, so I do believe this is really a bug. Apologies if this if my own fault.

Have another build from April 29th; no error in that version, but pronunciation is wrong.
Possibly introduced by fixes for issue #52?

This thing is pretty great btw; trying to generate speech for a technical presentation. The only hiccups
- sometimes needs misspelled words to improve pronunciation
- acronyms/jargon; any chance for SSML or other options to insert phonemes directly?

**Comment by svenha** [comment]
Same problem here for a fresh installation from https://github.com/rhasspy/piper/releases/download/v1.0.0/piper_amd64.tar.gz . Unfortunately, many words are affected, e.g. some numbers:

    echo "16 Computer" | ./piper -m de-thorsten-low.onnx -f test.wav

BTW: I managed to build piper also for a musl-based Linux (Alpine Linux / postmarketOS). If anyone uses such systems, please feel free to ask for details.

**Comment by synesthesiam** [comment]
This works now with Piper 1.1 and the "medium" Thorsten voice:

```sh
echo "manchmal" | ./piper -m de_DE-thorsten-medium.onnx -f test.wav
[2023-07-10 15:47:17.312] [piper] [info] Loaded voice in 0.163791197 second(s)
[2023-07-10 15:47:17.313] [piper] [info] Initialized piper
test.wav
[2023-07-10 15:47:17.344] [piper] [info] Real-time factor: 0.040793375220514114 (infer=0.02936383 sec, audio=0.7198185941043084 sec)
[2023-07-10 15:47:17.344] [piper] [info] Terminated piper
```

**Comment by synesthesiam** [comment]
The "low" quality voice will need to be retrained with additional phonemes.

**Comment by thorstenMueller** [comment]
Sorry for hopping in, but i'm just training a new Thorsten-Voice "high" model to be (hopefully) released in nearer future based on latest Piper sources 😊.
