### ISSUE TITLE
fails to install espeak-phonemizer windows 10

### ISSUE THREAD

**Issue by ArEnSc** [rhasspy/piper#111]
Collecting espeak-phonemizer==1.2.0
  Downloading espeak_phonemizer-1.2.0.tar.gz (17 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "c:\Users\Tensor\Desktop\piper\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\Users\Tensor\Desktop\piper\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\Users\Tensor\Desktop\piper\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel          return hook(config_settings)
        File "C:\Users\Tensor\AppData\Local\Temp\pip-build-env-mk3op46t\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel          return self._get_build_requires(config_settings, requirements=['wheel']) 
        File "C:\Users\Tensor\AppData\Local\Temp\pip-build-env-mk3op46t\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\Tensor\AppData\Local\Temp\pip-build-env-mk3op46t\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\Tensor\AppData\Local\Temp\pip-build-env-mk3op46t\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 16, in <module>
        File "C:\Users\Tensor\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1133, in read_text
          return f.read()
        File "C:\Users\Tensor\AppData\Local\Programs\Python\Python310\lib\encodings          return codecs.charmap_decode(input,self.errors,decoding_table)[0]        
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 707: character maps to <undefined>

**Comment by beqabeqa473** [comment]
which package are you trying to install?
i am not sure espeak-phonemizer from this organization will work on windows

**Comment by ArEnSc** [comment]
yeah that's what I figured it's strange though this would be the error lol and yeah that is the specific package trying to be installed

**Comment by rmcpantoja** [comment]
Hi @ArEnSc, 
try `pip install espeak-phonemizer-windows` instead.

**Comment by synesthesiam** [comment]
Piper will be using [piper-phonemize](https://github.com/rhasspy/piper-phonemize/) going forward. I will need some help porting that to Windows, but I don't expect it to be terribly difficult.

**Comment by kbickar** [comment]
So I've been running on windows a bit - there are some issues.

For espeak-phonemizer I was able to get around the issue of it not installing by manually extracting the package into the venv, but the bigger problem is the espeak_phonemizer lib has hardcoded dependencies on libc.so.6 and libespeak-ng.so.  The libespeak-ng.so is an easy swap for libespeak-ng.pyd, but the libc (which is just to get a file pointer buffer) doesn't have a Windows equivalent.  It looks like you corrected that in the piper-phonemize library so that's a big plus.  I'd love to be able to pass custom dictionary definitions for when the g2p process doesn't get it right, maybe something for the future

The other change was there's a step to call a script to cythonize the monotonic_align lib.   That's pretty easy to do manually (and move the .pyd file to the correct location), but obviously a shell script isn't working in Windows.

Everything else works fine on Windows.

**Comment by Artyom17** [comment]
I've created a PR (# 5) in espeak_phonemizer repo (https://github.com/rhasspy/espeak-phonemizer/pull/5) fix should fix this error.

**Comment by ph0enixph0enix** [comment]
I'm on windows 10 64 bit and running into the same issue. It seems to me that the PR #5 was not merged yet. As I understand it, it would make it possible to install on a windows 10 amd64 platform. Correct me if I'm wrong, please.

Could the PR #5 be integrated in the project so I can use Piper on my machine?

**Comment by rmcpantoja** [comment]
The #5 isn't related to this topic. piper_phonemize is already for Windows, we just have to wait for a Python wheel available for the pypy's repo.
