### ISSUE TITLE
ImportError when I attempt to train

### ISSUE THREAD

**Issue by StoryHack** [rhasspy/piper#132]
I am attempting to finetune the lessac high quality voice available on the hugginface page, using the Jenny Dioco dataset. I already reencoded all the recordings to 22050 bit rate and wav, then wrote a correct metadata.csv file with all the texts. I followed the training page and finally got to the step where I think I should be ready to run the training.

from the ./src/python directory, I run:

`python3 -m piper_train --dataset-dir ./training/jenny/ --accelerator 'gpu' --devices 1 --batch-size 16 --validation-split 0.05 --num-test-examples 5 --max_epochs 1000 --resume_from_checkpoint /ckpt/epoch=2218-step=838782.ckpt --checkpoint-epochs 1 --precision 32 --quality high`

I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/bryce/Apps/piper/src/python/piper_train/__main__.py", line 7, in <module>
    from pytorch_lightning import Trainer
  File "/home/bryce/Apps/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/bryce/Apps/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 25, in <module>
    from pytorch_lightning.callbacks.progress import ProgressBarBase, RichProgressBar, TQDMProgressBar
  File "/home/bryce/Apps/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/progress/__init__.py", line 22, in <module>
    from pytorch_lightning.callbacks.progress.rich_progress import RichProgressBar  # noqa: F401
  File "/home/bryce/Apps/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/progress/rich_progress.py", line 20, in <module>
    from torchmetrics.utilities.imports import _compare_version
ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports' (/home/bryce/Apps/piper/src/python/.venv/lib/python3.10/site-packages/torchmetrics/utilities/imports.py)

```
Any thoughts as to what I am doing wrong, or what I might not have installed correctly?

**Comment by rmcpantoja** [comment]
Hi @StoryHack, 
what version of pytorch-ligting are you using?
piper supports 1.7.7

**Comment by rmcpantoja** [comment]
Hi again @StoryHack, 
I've fixed the colab notebook. I added !pip install torchaudio==0.11.0 torchmetrics==0.11.4
[Here's the link](https://colab.research.google.com/github/rmcpantoja/piper/blob/master/notebooks/piper_multilingual_training_notebook.ipynb)

**Comment by beqabeqa473** [comment]
i was simply removing those packages with torch itself all together when i didn't have a gpu, and installing torch 1.13 with cuda support. With this setup everything is working.

**Comment by StoryHack** [comment]
@rmcpantoja I have pytorch-lightning~=1.7.0 listed in the requirements.txt

After searching around other projects and seeing similar issues, I added torchmetrics==0.11.4 to the requirements.txt file, and the error went away.

**Comment by cubedmeatgoeshere** [comment]
I'm having the same error as OP. Installed torchmetrics==0.11.4 but now I get a new error:

`Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/patrick/piper/src/python/piper_train/__main__.py", line 7, in <module>
    from pytorch_lightning import Trainer
  File "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/pruning.py", line 30, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 41, in <module>
    from pytorch_lightning.loggers import Logger, LoggerCollection
  File "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/loggers/__init__.py", line 23, in <module>
    from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
  File "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/loggers/tensorboard.py", line 26, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 26, in <module>
    from .summary import (
  File "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/torch/utils/tensorboard/summary.py", line 10, in <module>
    from six.moves import range
ModuleNotFoundError: No module named 'six'`

**Comment by beqabeqa473** [comment]
pip install six

On 9/22/23, cubedmeatgoeshere ***@***.***> wrote:
> I'm having the same error as OP. Installed torchmetrics==0.11.4 but now I
> get a new error:
>
> `Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/home/patrick/piper/src/python/piper_train/__main__.py", line 7, in
> <module>
>     from pytorch_lightning import Trainer
>   File
> "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/__init__.py",
> line 34, in <module>
>     from pytorch_lightning.callbacks import Callback  # noqa: E402
>   File
> "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py",
> line 26, in <module>
>     from pytorch_lightning.callbacks.pruning import ModelPruning
>   File
> "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/pruning.py",
> line 30, in <module>
>     from pytorch_lightning.core.module import LightningModule
>   File
> "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/core/__init__.py",
> line 16, in <module>
>     from pytorch_lightning.core.module import LightningModule
>   File
> "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/core/module.py",
> line 41, in <module>
>     from pytorch_lightning.loggers import Logger, LoggerCollection
>   File
> "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/loggers/__init__.py",
> line 23, in <module>
>     from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
>   File
> "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/loggers/tensorboard.py",
> line 26, in <module>
>     from torch.utils.tensorboard import SummaryWriter
>   File
> "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/torch/utils/tensorboard/__init__.py",
> line 12, in <module>
>     from .writer import FileWriter, SummaryWriter  # noqa: F401
>   File
> "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py",
> line 26, in <module>
>     from .summary import (
>   File
> "/home/patrick/piper/src/python/.venv/lib/python3.10/site-packages/torch/utils/tensorboard/summary.py",
> line 10, in <module>
>     from six.moves import range
> ModuleNotFoundError: No module named 'six'`
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/rhasspy/piper/issues/132#issuecomment-1731957012
> You are receiving this because you commented.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili
