### ISSUE TITLE
INVALID_PROTOBUF

### ISSUE THREAD

**Issue by trufae** [rhasspy/piper#190]
I tried building piper from git (on Ubuntu22, because i saw some blobs that are commited into the git that are linux-specific), but the build instructions are missing, so i just unpacked the tarball and put the includes int he right place to make it compile, but then its fialing because of missing phoneme_ids.hpp.., etc

At this point I decided to build it using Docker, which doesnt work at all with an "invalid reference format" error.

At this point there was no other option than downloading precompiled binaries, which is always my last option. Got the last ones from the release page https://github.com/rhasspy/piper/releases/tag/v1.2.0 and that was asserting with an error trying to parsed the onnx files.

Then I find out there was another precompiled version of piper in pip. So i tried it out and this is the outcome:

```
$ piper -m ca_ES-upc_ona-x_low.onnx
\Traceback (most recent call last):
  File "/home/pancake/.local/bin/piper", line 8, in <module>
    sys.exit(main())
  File "/home/pancake/.local/lib/python3.10/site-packages/piper/__main__.py", line 108, in main
    voice = PiperVoice.load(args.model, config_path=args.config, use_cuda=args.cuda)
  File "/home/pancake/.local/lib/python3.10/site-packages/piper/voice.py", line 39, in load
    session=onnxruntime.InferenceSession(
  File "/home/pancake/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/pancake/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ca_ES-upc_ona-x_low.onnx failed:Protobuf parsing failed.
```

The onnx models are taken from the hugging face git, as pointed out by the readme. and this error message suggests, and this is in theory the 1.2.0 version, aka the same as the last release from August.

`Downloading piper_tts-1.2.0-py3-none-any.whl (29 kB) ...`

Googling for this error message it points out that it's because the model is referencing external data, and this was fixed in December 2022, as all the tickets associated with the issue are closed and everything was merged.

So I wonder where's the problem here. If am I doing anything wrong, I would appreciate to have a working Dockerfile, a README with build instructions and a Makefile that unpacks all the dependencies in the right place.

PD: I tested different onnx files, not just the catalan one, and i got the same error with all of them.

**Comment by trufae** [comment]
Turns out the onnx files that work are the ones found in the tagged (not released) in this link https://github.com/rhasspy/piper/releases/tag/v0.0.2 by the version and the location it seems wrong to me, as blobs should never be commited into source repositories and those seems to be located in a separate repo. but at least i manage to get it to work and i'm amazed by the quality! So very good work everyone involved here, I hope soon we can have a decent free TTS that runs in local everywhere!

**Comment by docelic** [comment]
Hello,
You may be referring to the issue caused by the repository containing "Git Large File Storage" files (https://git-lfs.com/).
So instead of the actual (big) .onnx files in say, `en/en_US/ryan/high/`, those files may just be references to blobs, which could be confirmed by their small size.
Users need to install `git-lfs` and then run `git lfs fetch; git lfs checkout` to get the actual files (currently around 9GB of total size).
Hope it helps.
