### ISSUE TITLE
Error on start up: "KeyError: 'dataset'INFO: Service exited with code 1 (by signal 0)"

### ISSUE THREAD

**Issue by neekul** [rhasspy/piper#198]
Since around the 24th of Aug Piper Add On no longer started up.

I have pasted the log form the Add On as it tries to start up.

No errors in Core Logs

Only log in Supervisor Logs

```
23-09-06 11:10:50 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-piper with version 1.3.2
23-09-06 11:12:50 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Piper to start, took more then 120 seconds
```

Add On Log

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service piper: starting
s6-rc: info: service piper successfully started
s6-rc: info: service discovery: starting
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/__main__.py", line 193, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/__main__.py", line 131, in main
    custom_name = custom_config["dataset"]
                  ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'dataset'
[11:10:53] INFO: Service exited with code 1 (by signal 0)```

**Comment by neekul** [comment]
Uninstalled the addon, and reinstalled. Fixed whatever this issue is. Seems like the root cause was never found.
