### ISSUE TITLE
pip install dependancy conflict on Raspbian Pi 4

### ISSUE THREAD

**Issue by Esshahn** [rhasspy/piper#203]
When trying to install via `pip3 install piper-tts` I get this error:

````
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: piper-tts in /home/pi/.local/lib/python3.9/site-packages (1.2.0)
Collecting piper-tts
  Using cached piper_tts-1.2.0-py3-none-any.whl (29 kB)
  Using cached piper_tts-1.1.0-py3-none-any.whl (27 kB)
ERROR: Cannot install piper-tts==1.1.0 and piper-tts==1.2.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    piper-tts 1.2.0 depends on piper-phonemize~=1.1.0
    piper-tts 1.1.0 depends on piper-phonemize~=1.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
````

Any idea how to fix this?

**Comment by yiminghan** [comment]
same issue here

**Comment by mirfan899** [comment]
Use Python 3.9

**Comment by yiminghan** [comment]
similar issue with python3.9
```
yiminghan@raspberrypi:~/Documents/speak_server $ python3.9 -m pip install piper-tts
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting piper-tts
  Obtaining dependency information for piper-tts from https://files.pythonhosted.org/packages/24/aa/215bced0725cf5b5afe939f86b177c8ddb0d38292a94e85c55b3fcf6d46d/piper_tts-1.2.0-py3-none-any.whl.metadata
  Using cached piper_tts-1.2.0-py3-none-any.whl.metadata (776 bytes)
INFO: pip is looking at multiple versions of piper-tts to determine which version is compatible with other requirements. This could take a while.
  Obtaining dependency information for piper-tts from https://files.pythonhosted.org/packages/2e/1c/cc3a342db7f03053eca4fa5b05362178a5a796115770b216740b733b24d7/piper_tts-1.1.0-py3-none-any.whl.metadata
  Using cached piper_tts-1.1.0-py3-none-any.whl.metadata (776 bytes)
ERROR: Cannot install piper-tts==1.1.0 and piper-tts==1.2.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    piper-tts 1.2.0 depends on piper-phonemize~=1.1.0
    piper-tts 1.1.0 depends on piper-phonemize~=1.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

```
yiminghan@raspberrypi:~/Documents/speak_server $ python --version
Python 3.9.2
yiminghan@raspberrypi:~/Documents/speak_server $ 
yiminghan@raspberrypi:~/Documents/speak_server $ pip3 --version
pip 23.2.1 from /home/yiminghan/.local/lib/python3.9/site-packages/pip (python 3.9)
```

**Comment by synesthesiam** [comment]
What happens if you try to install `piper-phonemize` alone?

**Comment by Esshahn** [comment]
Not sure if that helps anybody else, but I did a clean install of Rasbian 64bit desktop and on that it worked on first try.

**Comment by athomas404** [comment]
I'm interested in trying to get this working on windows, I but I understand this probably means I'd need to do a whole-ass port myself. Never done this before, but it seems like a good thing to learn how to do. Before I dive into what changes to the code I might need to make before attempting to use VS build tools though, might the devs know off the top of their heads where the main pain points might be?

**Comment by yiminghan** [comment]
> What happens if you try to install `piper-phonemize` alone?

it looks like piper-phonemize is not being resolved

```
python3 -m pip install piper-phonemize~=1.1.0
ERROR: Could not find a version that satisfies the requirement piper-phonemize~=1.1.0 (from versions: none)
ERROR: No matching distribution found for piper-phonemize~=1.1.0
```

**Comment by synesthesiam** [comment]
@yiminghan Can you please run this?

```sh
python3 -m pip install -vvv piper-phonemize
```

**Comment by synesthesiam** [comment]
> I'm interested in trying to get this working on windows, I but I understand this probably means I'd need to do a whole-ass port myself. Never done this before, but it seems like a good thing to learn how to do. Before I dive into what changes to the code I might need to make before attempting to use VS build tools though, might the devs know off the top of their heads where the main pain points might be?

A Windows version of Piper already exists; the `piper-phonemize` Python package just needs to be built for Windows too.

**Comment by gns23** [comment]
Same issue, tried running python3 -m pip install -vvv piper-phonemize

result:

user@raspi:~ $ python3 -m pip install -vvv piper-phonemize
Using pip 23.2.1 from /home/user/.local/lib/python3.9/site-packages/pip (python 3.9)
Defaulting to user installation because normal site-packages is not writeable
Created temporary directory: /tmp/pip-build-tracker-rigi73g6
Initialized build tracking at /tmp/pip-build-tracker-rigi73g6
Created build tracker: /tmp/pip-build-tracker-rigi73g6
Entered build tracker: /tmp/pip-build-tracker-rigi73g6
Created temporary directory: /tmp/pip-install-ztcet92u
Created temporary directory: /tmp/pip-ephem-wheel-cache-g4761d8f
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
2 location(s) to search for versions of piper-phonemize:
* https://pypi.org/simple/piper-phonemize/
* https://www.piwheels.org/simple/piper-phonemize/
Fetching project page and analyzing links: https://pypi.org/simple/piper-phonemize/
Getting page https://pypi.org/simple/piper-phonemize/
Found index url https://pypi.org/simple/
Looking up "https://pypi.org/simple/piper-phonemize/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/piper-phonemize/ HTTP/1.1" 304 0
Fetched page https://pypi.org/simple/piper-phonemize/ as application/vnd.pypi.simple.v1+json
  Skipping link: none of the wheel's tags (cp310-cp310-manylinux_2_28_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/41/e8/ae6a5f5d23b7f35d29927bedc796e50d9c41ff03a2e3267100bdaeb3ba09/piper_phonemize-1.0.0-cp310-cp310-manylinux_2_28_aarch64.whl (from https://pypi.org/simple/piper-phonemize/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags (cp310-cp310-manylinux_2_28_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/9f/ef/71ba1cc30d8f5d9d98797e75ee1b9e096053ae83ad275eadee8a02303ddd/piper_phonemize-1.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (from https://pypi.org/simple/piper-phonemize/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags (cp311-cp311-manylinux_2_28_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/ed/02/0b68b01b4c3db09ea7daef6f20f8f9b9d2bf2e3dc5e6bacd09db034d54fd/piper_phonemize-1.0.0-cp311-cp311-manylinux_2_28_aarch64.whl (from https://pypi.org/simple/piper-phonemize/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags (cp311-cp311-manylinux_2_28_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/d7/e3/e337d412d3afd10d929d4b43ceb8aa37a244a9821049e598e7dcfcbd50ea/piper_phonemize-1.0.0-cp311-cp311-manylinux_2_28_x86_64.whl (from https://pypi.org/simple/piper-phonemize/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags (cp39-cp39-manylinux_2_28_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/7e/15/7dcf261a3ed1c800605198950c236bcfcf988063a220dedcb31e9f795817/piper_phonemize-1.0.0-cp39-cp39-manylinux_2_28_aarch64.whl (from https://pypi.org/simple/piper-phonemize/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags (cp39-cp39-manylinux_2_28_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/21/7e/531eaccb5794681c262d71f1d1017a24b37077154e3b02dd7eb883ea4fcf/piper_phonemize-1.0.0-cp39-cp39-manylinux_2_28_x86_64.whl (from https://pypi.org/simple/piper-phonemize/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags (cp310-cp310-manylinux_2_28_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/66/ca/65e4cee554554a648af9cca6ce4ab7f14ea9ea62f1d77b2f53fbcf3329e4/piper_phonemize-1.1.0-cp310-cp310-manylinux_2_28_aarch64.whl (from https://pypi.org/simple/piper-phonemize/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags (cp310-cp310-manylinux_2_28_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/e9/e0/17c224e4a2a78c7fdd7c0a680693b1753293384ddfe860550950ed9b7e97/piper_phonemize-1.1.0-cp310-cp310-manylinux_2_28_x86_64.whl (from https://pypi.org/simple/piper-phonemize/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags (cp311-cp311-manylinux_2_28_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/6f/eb/02440084802648a3e074c0db9a72dfbbce35f4110ed3db085129d5dca7bc/piper_phonemize-1.1.0-cp311-cp311-manylinux_2_28_aarch64.whl (from https://pypi.org/simple/piper-phonemize/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags (cp311-cp311-manylinux_2_28_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/b8/b7/a8fc2584d509ca36d5713693d675a88f80e4c3725e16a8c7ff1451f0ba99/piper_phonemize-1.1.0-cp311-cp311-manylinux_2_28_x86_64.whl (from https://pypi.org/simple/piper-phonemize/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags (cp39-cp39-manylinux_2_28_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/af/2d/bd071a6d73c7faab15d36fca90a2dd6245e03e40454dee5a13538cf223a6/piper_phonemize-1.1.0-cp39-cp39-manylinux_2_28_aarch64.whl (from https://pypi.org/simple/piper-phonemize/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags (cp39-cp39-manylinux_2_28_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/32/8b/c480d8d4e71fcbcf2ff9fe574ead95ad96b63886acbdff4dc70479ff2bcd/piper_phonemize-1.1.0-cp39-cp39-manylinux_2_28_x86_64.whl (from https://pypi.org/simple/piper-phonemize/) (requires-python:>=3.7)
Fetching project page and analyzing links: https://www.piwheels.org/simple/piper-phonemize/
Getting page https://www.piwheels.org/simple/piper-phonemize/
Found index url https://www.piwheels.org/simple/
Looking up "https://www.piwheels.org/simple/piper-phonemize/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): www.piwheels.org:443
https://www.piwheels.org:443 "GET /simple/piper-phonemize/ HTTP/1.1" 200 115
Updating cache with response from "https://www.piwheels.org/simple/piper-phonemize/"
etag object cached for 1209600 seconds
Caching due to etag
Fetched page https://www.piwheels.org/simple/piper-phonemize/ as text/html
Skipping link: not a file: https://www.piwheels.org/simple/piper-phonemize/
Skipping link: not a file: https://pypi.org/simple/piper-phonemize/
Given no hashes to check 0 links for project 'piper-phonemize': discarding no candidates
ERROR: Could not find a version that satisfies the requirement piper-phonemize (from versions: none)
ERROR: No matching distribution found for piper-phonemize
Exception information:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/user/.local/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 174, in _add_to_criteria
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('piper-phonemize')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/home/user/.local/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/user/.local/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 399, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('piper-phonemize'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/user/.local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/home/user/.local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/home/user/.local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 101, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: No matching distribution found for piper-phonemize
Remote version of pip: 23.2.1
Local version of pip:  23.2.1
Was pip installed by pip? True
Removed build tracker: '/tmp/pip-build-tracker-rigi73g6'
user@raspi:~ $

**Comment by synesthesiam** [comment]
Are you on a 32-bit OS?

**Comment by gns23** [comment]
it's 64-bit:

user@raspi:~ $ uname -m
aarch64

**Comment by synesthesiam** [comment]
Ok, and what glibc version? Can you run "ldd --version" and give the output please?
This has to be it 😄

**Comment by gns23** [comment]
what version would be correct? here we go:

user@raspi:~ $ ldd --version
ldd (Debian GLIBC 2.31-13+rpt2+rpi1+deb11u5) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
user@raspi:~ $

**Comment by eshack94** [comment]
I'm seeing the same issue on MacOS (ARM64).

**Comment by melMass** [comment]
I have the same issue on windows 11 with python 3.10.11:

```console
> pip install piper-tts
Collecting piper-tts
  Downloading piper_tts-1.2.0-py3-none-any.whl (29 kB)
INFO: pip is looking at multiple versions of piper-tts to determine which version is compatible with other requirements. This could take a while.
  Downloading piper_tts-1.1.0-py3-none-any.whl (27 kB)

The conflict is caused by:
    piper-tts 1.2.0 depends on piper-phonemize~=1.1.0
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

> pip install git+https://github.com/rhasspy/piper#egg=piper-tts&subdirectory=src/python_run
Collecting piper-tts
  Cloning https://github.com/rhasspy/piper to c:\users\user\appdata\local\temp\pip-install-7uvxeiv3\piper-tts_09ae3c53db4e47cdaf6187e381d03204
  Running command git clone --filter=blob:none --quiet https://github.com/rhasspy/piper 'C:\Users\User\AppData\Local\Temp\pip-install-7uvxeiv3\piper-tts_09ae3c53db4e47cdaf6187e381d03204'
  Resolved https://github.com/rhasspy/piper to commit 54fad0445ac9b7e734753fcb149c259caf1c0e30
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of piper-tts to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement piper-phonemize~=1.1.0 (from piper-tts) (from versions: none)
ERROR: No matching distribution found for piper-phonemize~=1.1.0
```

**Comment by pmcgaley** [comment]
Just did a bit more reading - it's very likely I what I installed is "Our recommended operating system for most users" (from https://www.raspberrypi.com/software/operating-systems/) which is the "32-bit" OS, but that now uses the 64-bit kernel (v 6.1), hence the confusion.

Worth noting then that the `uname` etc. on 32-bit Raspberry Pi OS installs now report `aarch64`, even though they'll still be running everything 32-bit. `file /bin/ls` will tell you if you're on actual 64-bit or not.

So I guess I'll need to decide whether a reinstall is worth the effort.

**Comment by gns23** [comment]
whoaa! thx for pointing out! could u let us now, if u get it to work with a reinst? atm i'm short of time to try myself..

**Comment by pmcgaley** [comment]
Confirmed that it works fine with the actual 64-bit install of Rasperry Pi OS.

**Comment by gns23** [comment]
just installed the correct 64bit-version of Raspberry Pi OS and install of piper-tts was successful. it can be used with existing voices.  

thx again!
