### ISSUE TITLE
KeyError: 'dataset'

### ISSUE THREAD

**Issue by magnusoverli** [rhasspy/piper#205]
On adding a custom voice, the Piper Addon in Home Assistant throws this error:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/__main__.py", line 193, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/__main__.py", line 131, in main
    custom_name = custom_config["dataset"]
                  ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'dataset'
[21:30:14] INFO: Service exited with code 1 (by signal 0)
```
The voice is recorded using Piper Recording Studio, and trained using the Pyhton Piper Train module. Exported to onnx as per the documentation here: https://github.com/rhasspy/piper/blob/master/TRAINING.md

**Comment by synesthesiam** [comment]
I've just updated the preprocessing script to add the necessary pieces. You will need to add/merge these fields manually in to your config for now:

```json
{
  "dataset": "<name of your voice>",
  "audio": {
    "quality": "<x_low/low/medium/high>"
  },
  "language": {
    "code": "<example: en_US>"
  }
}
```

**Comment by magnusoverli** [comment]
Not sure this makes sense...?
```
{
    "dataset": "workspace",
    "audio": {
        "sample_rate": 22050,
        "quality": "preprocessed"
    },
    "espeak": {
        "voice": "nb"
    },
    "language": {
        "code": "nb"
    },
    "inference": {
        "noise_scale": 0.667,
        "length_scale": 1,
        "noise_w": 0.8
    },
...
```
The script seems to put directories into both the dataset key and the quality key?
