### ISSUE TITLE
Error during multi-GPU training

### ISSUE THREAD

**Issue by SedatDe** [rhasspy/piper#216]
Hello.

Training on a single GPU works fine.
However, if a number greater than 1 is given to the `--devices` parameter of `piper_train` it fails with the following trace.

```
Traceback (most recent call last):
  File "/miniconda3/envs/piper/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/miniconda3/envs/piper/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/piper/src/python/piper_train/__main__.py", line 150, in <module>
    main()
  File "/piper/src/python/piper_train/__main__.py", line 127, in main
    trainer.fit(model)
  File "/miniconda3/envs/piper/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/miniconda3/envs/piper/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 648, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/miniconda3/envs/piper/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 107, in launch
    mp.start_processes(
  File "/miniconda3/envs/piper/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 189, in start_processes
    process.start()
  File "/miniconda3/envs/piper/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/miniconda3/envs/piper/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/miniconda3/envs/piper/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/miniconda3/envs/piper/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/miniconda3/envs/piper/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/miniconda3/envs/piper/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/miniconda3/envs/piper/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 143, in reduce_tensor
    raise RuntimeError("Cowardly refusing to serialize non-leaf tensor which requires_grad, "
RuntimeError: Cowardly refusing to serialize non-leaf tensor which requires_grad, since autograd does not support crossing process boundaries.  If you just want to transfer the data, call detach() on the tensor before serializing (e.g., putting it on the queue).
```

What can be the possible cause, can you point me in the right direction to solve this issue?

**Comment by SedatDe** [comment]
Providing `--strategy ddp` resolved this issue.
