### ISSUE TITLE
Error while pre-processing

### ISSUE THREAD

**Issue by abcnm123456** [rhasspy/piper#220]
![WhatsApp Image 2023-09-22 at 20 29 46](https://github.com/rhasspy/piper/assets/25501502/a49dd951-69cf-4aca-9c0a-db09c31bdc48)
(.venv) user@DESKTOP-U00B88J:~/piper/src/python$ python -m piper_train.preprocess --input-dir ~/piper/DATASET/GoogleSmall --output-dir ~/piper/TRAINED --language en --sample-rate 16000 --dataset-format ljspeech
INFO:preprocess:Single speaker dataset
INFO:preprocess:Wrote dataset config
INFO:preprocess:Processing 4 utterance(s) with 16 worker(s)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/piper/src/python/piper_train/preprocess.py", line 473, in <module>
    main()
  File "/home/user/piper/src/python/piper_train/preprocess.py", line 202, in main
    for utt_batch in batched(
  File "/home/user/piper/src/python/piper_train/preprocess.py", line 462, in batched
    raise ValueError("n must be at least one")
ValueError: n must be at least one

**Comment by rmcpantoja** [comment]
Hi @abcnm123456, 
Your dataset is too short.
For fine-tuning, requires minimum 5 minutes of data to work better.

**Comment by coffeecodeconverter** [comment]
check out this article 
https://github.com/rhasspy/piper/issues/297

for the error:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ValueError: n must be at least one
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

setting 
~~~~~~~~~~~~~~~
--max-workers=1 
~~~~~~~~~~~~~~~
has solved it for some
