### ISSUE TITLE
how to infer multispeaker model during training

### ISSUE THREAD

**Issue by mirfan899** [rhasspy/piper#230]
I have 5 speakers in my dataset. How do I generate samples during training from checkpoints for a multi-speaker model? 
Here is my config.json
```json
{
    "dataset": "",
    "audio": {
        "sample_rate": 22050,
        "quality": "medium"
    },
    "espeak": {
        "voice": "en-us"
    },
    "language": {
        "code": "en-us"
    },
    "inference": {
        "noise_scale": 0.667,
        "length_scale": 1,
        "noise_w": 0.8
    },
    "phoneme_type": "espeak",
    "phoneme_map": {},
    "phoneme_id_map": {
        " ": [
            3
        ],
        "!": [
            4
        ],
        "\"": [
            150
        ],
        "#": [
            149
        ],
        "$": [
            2
        ],
        "'": [
            5
        ],
        "(": [
            6
        ],
        ")": [
            7
        ],
        ",": [
            8
        ],
        "-": [
            9
        ],
        ".": [
            10
        ],
        "0": [
            130
        ],
        "1": [
            131
        ],
        "2": [
            132
        ],
        "3": [
            133
        ],
        "4": [
            134
        ],
        "5": [
            135
        ],
        "6": [
            136
        ],
        "7": [
            137
        ],
        "8": [
            138
        ],
        "9": [
            139
        ],
        ":": [
            11
        ],
        ";": [
            12
        ],
        "?": [
            13
        ],
        "X": [
            156
        ],
        "^": [
            1
        ],
        "_": [
            0
        ],
        "a": [
            14
        ],
        "b": [
            15
        ],
        "c": [
            16
        ],
        "d": [
            17
        ],
        "e": [
            18
        ],
        "f": [
            19
        ],
        "g": [
            154
        ],
        "h": [
            20
        ],
        "i": [
            21
        ],
        "j": [
            22
        ],
        "k": [
            23
        ],
        "l": [
            24
        ],
        "m": [
            25
        ],
        "n": [
            26
        ],
        "o": [
            27
        ],
        "p": [
            28
        ],
        "q": [
            29
        ],
        "r": [
            30
        ],
        "s": [
            31
        ],
        "t": [
            32
        ],
        "u": [
            33
        ],
        "v": [
            34
        ],
        "w": [
            35
        ],
        "x": [
            36
        ],
        "y": [
            37
        ],
        "z": [
            38
        ],
        "æ": [
            39
        ],
        "ç": [
            40
        ],
        "ð": [
            41
        ],
        "ø": [
            42
        ],
        "ħ": [
            43
        ],
        "ŋ": [
            44
        ],
        "œ": [
            45
        ],
        "ǀ": [
            46
        ],
        "ǁ": [
            47
        ],
        "ǂ": [
            48
        ],
        "ǃ": [
            49
        ],
        "ɐ": [
            50
        ],
        "ɑ": [
            51
        ],
        "ɒ": [
            52
        ],
        "ɓ": [
            53
        ],
        "ɔ": [
            54
        ],
        "ɕ": [
            55
        ],
        "ɖ": [
            56
        ],
        "ɗ": [
            57
        ],
        "ɘ": [
            58
        ],
        "ə": [
            59
        ],
        "ɚ": [
            60
        ],
        "ɛ": [
            61
        ],
        "ɜ": [
            62
        ],
        "ɞ": [
            63
        ],
        "ɟ": [
            64
        ],
        "ɠ": [
            65
        ],
        "ɡ": [
            66
        ],
        "ɢ": [
            67
        ],
        "ɣ": [
            68
        ],
        "ɤ": [
            69
        ],
        "ɥ": [
            70
        ],
        "ɦ": [
            71
        ],
        "ɧ": [
            72
        ],
        "ɨ": [
            73
        ],
        "ɪ": [
            74
        ],
        "ɫ": [
            75
        ],
        "ɬ": [
            76
        ],
        "ɭ": [
            77
        ],
        "ɮ": [
            78
        ],
        "ɯ": [
            79
        ],
        "ɰ": [
            80
        ],
        "ɱ": [
            81
        ],
        "ɲ": [
            82
        ],
        "ɳ": [
            83
        ],
        "ɴ": [
            84
        ],
        "ɵ": [
            85
        ],
        "ɶ": [
            86
        ],
        "ɸ": [
            87
        ],
        "ɹ": [
            88
        ],
        "ɺ": [
            89
        ],
        "ɻ": [
            90
        ],
        "ɽ": [
            91
        ],
        "ɾ": [
            92
        ],
        "ʀ": [
            93
        ],
        "ʁ": [
            94
        ],
        "ʂ": [
            95
        ],
        "ʃ": [
            96
        ],
        "ʄ": [
            97
        ],
        "ʈ": [
            98
        ],
        "ʉ": [
            99
        ],
        "ʊ": [
            100
        ],
        "ʋ": [
            101
        ],
        "ʌ": [
            102
        ],
        "ʍ": [
            103
        ],
        "ʎ": [
            104
        ],
        "ʏ": [
            105
        ],
        "ʐ": [
            106
        ],
        "ʑ": [
            107
        ],
        "ʒ": [
            108
        ],
        "ʔ": [
            109
        ],
        "ʕ": [
            110
        ],
        "ʘ": [
            111
        ],
        "ʙ": [
            112
        ],
        "ʛ": [
            113
        ],
        "ʜ": [
            114
        ],
        "ʝ": [
            115
        ],
        "ʟ": [
            116
        ],
        "ʡ": [
            117
        ],
        "ʢ": [
            118
        ],
        "ʦ": [
            155
        ],
        "ʰ": [
            145
        ],
        "ʲ": [
            119
        ],
        "ˈ": [
            120
        ],
        "ˌ": [
            121
        ],
        "ː": [
            122
        ],
        "ˑ": [
            123
        ],
        "˞": [
            124
        ],
        "ˤ": [
            146
        ],
        "̃": [
            141
        ],
        "̧": [
            140
        ],
        "̩": [
            144
        ],
        "̪": [
            142
        ],
        "̯": [
            143
        ],
        "̺": [
            152
        ],
        "̻": [
            153
        ],
        "β": [
            125
        ],
        "ε": [
            147
        ],
        "θ": [
            126
        ],
        "χ": [
            127
        ],
        "ᵻ": [
            128
        ],
        "↑": [
            151
        ],
        "↓": [
            148
        ],
        "ⱱ": [
            129
        ]
    },
    "num_symbols": 256,
    "num_speakers": 904,
    "speaker_id_map": {
        "1": 0,
        "4": 1,
        "0": 2,
        "3": 3,
        "2": 4
    },
    "piper_version": "1.0.0"
}

```
Tried to use --speaker-id and --speaker parameter. 
I also wanted to use it in a JSONL file.
```jsonl
{"text": "It takes the form of a multi-colored circular arc.", "phonemes": ["ɪ", "t", " ", "t", "ˈ", "e", "ɪ", "k", "s", " ", "ð", "ə", " ", "f", "ˈ", "ɔ", "ː", "ɹ", "m", " ", "ə", "v", "ə", " ", "m", "ˈ", "ʌ", "l", "t", "a", "ɪ", "k", "ˈ", "ʌ", "l", "ɚ", "d", " ", "s", "ˈ", "ɜ", "ː", "k", "j", "ʊ", "l", "ɚ", "ɹ", " ", "ˈ", "ɑ", "ː", "ɹ", "k", "."], "phoneme_ids": [1, 0, 74, 0, 32, 0, 3, 0, 32, 0, 120, 0, 18, 0, 74, 0, 23, 0, 31, 0, 3, 0, 41, 0, 59, 0, 3, 0, 19, 0, 120, 0, 54, 0, 122, 0, 88, 0, 25, 0, 3, 0, 59, 0, 34, 0, 59, 0, 3, 0, 25, 0, 120, 0, 102, 0, 24, 0, 32, 0, 14, 0, 74, 0, 23, 0, 120, 0, 102, 0, 24, 0, 60, 0, 17, 0, 3, 0, 31, 0, 120, 0, 62, 0, 122, 0, 23, 0, 22, 0, 100, 0, 24, 0, 60, 0, 88, 0, 3, 0, 120, 0, 51, 0, 122, 0, 88, 0, 23, 0, 10, 0, 2], "speaker": 0}

```

gives error for all these options.
```shell
cat test.jsonl |     python3 -m piper_train.infer         --sample-rate 22050         --checkpoint /home/user/piper/src/python/processed/lightning_logs/version_0/checkpoints/epoch=417-step=1916264.ckpt         --output-dir /home/user/piper/src/python/generated
DEBUG:fsspec.local:open file: /home/user/piper/src/python/processed/lightning_logs/version_0/checkpoints/epoch=417-step=1916264.ckpt
```
Error
```shell
DEBUG:vits.lightning:No dataset to load
Removing weight norm...
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/.pyenv/versions/3.10.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/piper/src/python/piper_train/infer.py", line 79, in <module>
    main()
  File "/home/user/piper/src/python/piper_train/infer.py", line 56, in main
    audio = model(text, text_lengths, scales, sid=sid).detach().numpy()
  File "/home/user/.pyenv/versions/train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/piper/src/python/piper_train/vits/lightning.py", line 145, in forward
    audio, *_ = self.model_g.infer(
  File "/home/user/piper/src/python/piper_train/vits/models.py", line 693, in infer
    assert sid is not None, "Missing speaker id"
AssertionError: Missing speaker id

```

**Comment by mirfan899** [comment]
okya, after checking piper_train, got it working. The key for speaker is `speaker_id`.
