### ISSUE TITLE
Terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_2::detail::parse_error'

### ISSUE THREAD

**Issue by BlackBatA8T** [rhasspy/piper#233]
Hello, I am trying to get this working on a Raspberry Pi 4B and have had some troubles. I get an error 

```
terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_2::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '<'
Aborted
```

I am using the [1.2.0](https://github.com/rhasspy/piper/releases/tag/v1.2.0) ARM64 on the latest Raspberry Pi OS lite [64 bit] but have also tried the ARMv7 file and the 32 Bit OS but got the same issues and am using the en_GB-northern_english_male-medium voice model. Using the `--debug` flag doesn't produce any useful information. I am using SSH but I don't see how that should effect it.

**Comment by undrwater** [comment]
Running into the same error on x86_64. 

The voice I'm using is: en_US-libritts_r-medium.onnx

Thank you in advance.

**Comment by pjarmuzek** [comment]
Hello,

I'm getting the same effect on:
RPI CM4 (64bit kernel, and 32-bit userland)
Intel x86_64
Both having the same error. No matter if I compiled from source, or used precombiled latest binaries. Tried using: pl_PL-gosia-medium.onnx

**Comment by BlackBatA8T** [comment]
I was able to fix it by following the [Running in Python](https://github.com/rhasspy/piper#running-in-python) section to download my model file. @pjarmuzek  @undrwater If you follow those steps does it work?

**Comment by pjarmuzek** [comment]
@BlackBatA8T 
I've got both model and json files downloaded in the same dir where piper is located:

```
root@xxxxxx:/mnt/nand-user/temp/source/piper # ls
espeak-ng-data   libespeak-ng.so.1       libonnxruntime.so         libpiper_phonemize.so    libpiper_phonemize.so.1.1.0  piper                    pl_PL-gosia-medium.onnx.json
libespeak-ng.so  libespeak-ng.so.1.1.51  libonnxruntime.so.1.14.1  libpiper_phonemize.so.1  libtashkeel_model.ort        pl_PL-gosia-medium.onnx
root@xxxxxx:/mnt/nand-user/temp/source/piper # echo "test" | ./piper -m pl_PL-gosia-medium.onnx -c pl_PL-gosia-medium.onnx.json -f output.wav
terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_2::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '<'
Aborted
```

**Comment by pjarmuzek** [comment]
@BlackBatA8T 
Downloaded from: https://huggingface.co/rhasspy/piper-voices/tree/v1.0.0

It looks like that I got the wrong files downloaded.. Now after your message checked repo again, re-downloaded and it's fine. Piper correctly outputs the wav file :)

**Comment by undrwater** [comment]
> I was able to fix it by following the [Running in Python](https://github.com/rhasspy/piper#running-in-python) section to download my model file then using it in the c++ binary. @pjarmuzek @undrwater If you follow those steps does it work?

Kind of. For some reason it doesn't find some of the voices to download. Example:

`echo 'Welcome to the world of speech synthesis!' | piper   --model en_US-libritts_r-medium --output_file welcome.wav
Traceback (most recent call last):
  File "/srv/piper/bin/piper", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/srv/piper/lib/python3.11/site-packages/piper/__main__.py", line 104, in main
    ensure_voice_exists(args.model, args.data_dir, args.download_dir, voices_info)
  File "/srv/piper/lib/python3.11/site-packages/piper/download.py", line 56, in ensure_voice_exists
    raise VoiceNotFoundError(name)
piper.download.VoiceNotFoundError: en_US-libritts_r-medium`

That file is at the same hugging face URL from above, and follows the same convention for the 'lessac' voice. Some other voices such as 'joe' work, and others do not. I suspect it's a parsing error.

**Comment by undrwater** [comment]
Actually, I downloaded the en_US-libritts_r-medium.onnx file and it is quite a bit smaller than the others. 40k vs ~61M for the ones that work. Perhaps some of the files were not correctly built?

Would that be better as a new issue?

**Comment by Sponsoredby** [comment]
is there any udate to this i am still getting this issue, i tried the solution about following the running in pythin and that led to a sepearte issue

**Comment by JensC** [comment]
THe same here too on a Jetson nano, arm64 binary. Tried several voices without any luck. Help would be really appreciated.

**Comment by synesthesiam** [comment]
If your file is only 40K, you are probably downloading the huggingface web page *about* the file, and not the file itself.

URL for the page: https://huggingface.co/rhasspy/piper-voices/blob/main/en/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx
URL for the file: https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx

Notice the `blob` vs `resolve` difference.
