### ISSUE TITLE
preprocess error

### ISSUE THREAD

**Issue by RoxBlox3** [rhasspy/piper#246]
![image](https://github.com/rhasspy/piper/assets/122562352/529bf0c0-6154-4d45-a894-a9f655a01366)
(.venv) roxblox@PCRoxBlox:~/piper/src/python$ python3 -m piper_train.preprocess --language en --input-dir ~/piper/GLaDOS-Dataset --output-dir ~/piper/my-training --dataset-format ljspeech --single-speaker --sample-rate 22050
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/roxblox/piper/src/python/piper_train/preprocess.py", line 502, in <module>
    main()
  File "/home/roxblox/piper/src/python/piper_train/preprocess.py", line 143, in main
    for utt in make_dataset(args):
  File "/home/roxblox/piper/src/python/piper_train/preprocess.py", line 423, in ljspeech_dataset
    assert len(row) >= 2, "Not enough columns"
AssertionError: Not enough columns

I am on WSL from windows 10.

**Comment by rmcpantoja** [comment]
Hi @RoxBlox3, 
It seems that your transcription is not correct. Are you sure the transcription syntax is audio|text? (in case of LJSpeech)

**Comment by RoxBlox3** [comment]
@rmcpantoja Thank you for the response. I think so ? 
here's an example of lines but perhaps it's things like ponctuation. I'm quite new to all this so idk.

a2_triple_laser01|Federal regulations require me to warn you that this next test chamber... is looking pretty good.
a2_triple_laser02|That's right. The facility is completely operational again.
a2_triple_laser03|I think these test chambers look even better than they did before. It was easy, really. You just have to look at things objectively, see what you don't need anymore, and trim out the fat.
chellgladoswakeup01|Oh... It's you.
chellgladoswakeup04|It's been a long time. How have you been?
chellgladoswakeup05|I've been really busy being dead. You know, after you MURDERED ME.
chellgladoswakeup06|Okay. Look. We both said a lot of things that you're going to regret. But I think we can put our differences behind us. For science. You monster.
epilogue03|Oh thank god, you're alright.

**Comment by Ac3inSpac3** [comment]
I am having the same issue as well, did you ever find out what was wrong?

**Comment by XKenixs** [comment]
Hi @Ac3inSpac3,
I had the same issue. the pipes werent registered as delimiter. A short python script can replace those characters.
Try 
`import csv

def process_file_with_pipes_as_delimiter(input_filename):
    processed_data = []
    with open(input_filename, 'r', encoding='utf-8') as file:
        for line in file:
            #if line is not empty
            if line.strip() == '':
                continue
            fields = line.strip().split('|')
            processed_data.append(fields)
    return processed_data

def write_processed_data_to_csv(output_filename, data, delimiter='|'):
    with open(output_filename, 'w', encoding='utf-8', newline='') as csvfile:
        writer = csv.writer(csvfile, delimiter=delimiter, quotechar='"', quoting=csv.QUOTE_MINIMAL)
        for row in data:
            writer.writerow(row)

def main():
    input_filename = 'metadata.csv' #input file
    output_filename = 'output.csv' #output file
    processed_data = process_file_with_pipes_as_delimiter(input_filename)
    write_processed_data_to_csv(output_filename, processed_data, delimiter='|')

if __name__ == '__main__':
    main()
`

**Comment by SyedMuqtasidAli** [comment]
> ![image](https://private-user-images.githubusercontent.com/122562352/276654828-529bf0c0-6154-4d45-a894-a9f655a01366.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODY1NDcsIm5iZiI6MTcxMjM4NjI0NywicGF0aCI6Ii8xMjI1NjIzNTIvMjc2NjU0ODI4LTUyOWJmMGMwLTYxNTQtNGQ0NS1hODk0LWE5ZjY1NWEwMTM2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNlQwNjUwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTU3NDE2YjA0NTVlNTg0ZjBjYWZkMTBkYjJlMzIzOGQxMGFmYjg2YTQxZTYzY2I4NWZhZWY2OTA2M2ZhN2Y5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tRKJ1DWP7tOAaYSlZddVn4gw0d6Y6dUZUUrGF7eqRCo) (.venv) roxblox@PCRoxBlox:~/piper/src/python$ python3 -m piper_train.preprocess --language en --input-dir ~/piper/GLaDOS-Dataset --output-dir ~/piper/my-training --dataset-format ljspeech --single-speaker --sample-rate 22050 Traceback (most recent call last): File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/home/roxblox/piper/src/python/piper_train/preprocess.py", line 502, in main() File "/home/roxblox/piper/src/python/piper_train/preprocess.py", line 143, in main for utt in make_dataset(args): File "/home/roxblox/piper/src/python/piper_train/preprocess.py", line 423, in ljspeech_dataset assert len(row) >= 2, "Not enough columns" AssertionError: Not enough columns
> 
> I am on WSL from windows 10.

did you find solution ?

**Comment by SyedMuqtasidAli** [comment]
@RoxBlox3

**Comment by RoxBlox3** [comment]
> > ![image](https://private-user-images.githubusercontent.com/122562352/276654828-529bf0c0-6154-4d45-a894-a9f655a01366.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODY1NDcsIm5iZiI6MTcxMjM4NjI0NywicGF0aCI6Ii8xMjI1NjIzNTIvMjc2NjU0ODI4LTUyOWJmMGMwLTYxNTQtNGQ0NS1hODk0LWE5ZjY1NWEwMTM2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNlQwNjUwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTU3NDE2YjA0NTVlNTg0ZjBjYWZkMTBkYjJlMzIzOGQxMGFmYjg2YTQxZTYzY2I4NWZhZWY2OTA2M2ZhN2Y5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tRKJ1DWP7tOAaYSlZddVn4gw0d6Y6dUZUUrGF7eqRCo) (.venv) roxblox@PCRoxBlox:~/piper/src/python$ python3 -m piper_train.preprocess --language en --input-dir ~/piper/GLaDOS-Dataset --output-dir ~/piper/my-training --dataset-format ljspeech --single-speaker --sample-rate 22050 Traceback (most recent call last): File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/home/roxblox/piper/src/python/piper_train/preprocess.py", line 502, in main() File "/home/roxblox/piper/src/python/piper_train/preprocess.py", line 143, in main for utt in make_dataset(args): File "/home/roxblox/piper/src/python/piper_train/preprocess.py", line 423, in ljspeech_dataset assert len(row) >= 2, "Not enough columns" AssertionError: Not enough columns
> > I am on WSL from windows 10.
> 
> did you find solution ?

No but it is probably an error with my transcription when i tried with another transcription file it worked in the end i did not finish making a new voice as someone made on much better than what i could do so i did not continue.

**Comment by saikewei** [comment]
I had the same issue. And i finally find out that's because i use `pandas` to delete some columns of the csv file, then i forgot to set the delimiter to '|', which became default comma

**Comment by coffeecodeconverter** [comment]
for clarity, the punctuation wont be a problem, in case anyone was wondering. 
as long as for single speakers, the format is (it can work with or without the .wav file extension)
~~~~~~~~~~~
filename|transcription 
~~~~~~~~~~~

and for multiple speakers, the format is 
~~~~~~~~~~~
filename|speaker|transcription 
~~~~~~~~~~~

one thing that will give you an issue though, is if the transcription line is too long, 
i haven't found the exact limit, but if you opened your metadata.csv in notepad and a single line is wrapping round by several lines, its too long, and should aim to have one transcription per line only, short enough so it DOESN'T wrap at least, that seems to be a decent line in the sand to avoid from my experience. 

as others have said, the main reason your likely getting the error is due to the delimiter. 
either the file is not correctly formatted as a pipe-delimited file, 
or the script reading the file fails to look for the pipe as the delimiter. 

for example, notepad.exe might show 
~~~~~~~~~~~
filename|transcription 
~~~~~~~~~~~

but its if formatted as comma delimited, it might actually be interpreted as
~~~~~~~~~~~
filename|,transcription 
~~~~~~~~~~~
so try opening in notepad++ instead 
which can re-save it in pipe-delimited format.

**Comment by johnem-msft** [comment]
Issue is due to blank/extran lines in the CSV

For me, anyway I got error: 

   assert len(row) >= 2, "Not enough columns"
AssertionError: Not enough columns

Because:  I had two blank lines at the end of the file 
Deleted those two blank lines at the end (carriage returns), fixed the issue.
