### ISSUE TITLE
Training notebook error caused it to stop training

### ISSUE THREAD

**Issue by MooTheCow** [rhasspy/piper#311]
DEBUG:fsspec.local:open file: /content/drive/MyDrive/colab/piper/Test/lightning_logs/version_0/checkpoints/last.ckpt
Epoch: 2632. Steps: 1363964
warning: audio amplitude out of range, auto clipped.
DEBUG:fsspec.local:open file: /content/drive/MyDrive/colab/piper/Test/lightning_logs/version_0/checkpoints/last.ckpt
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/cloud_io.py", line 68, in atomic_save
    f.write(bytesbuffer.getvalue())
  File "/usr/local/lib/python3.10/dist-packages/fsspec/implementations/local.py", line 382, in write
    return self.f.write(*args, **kwargs)
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/piper/src/python/piper_train/__main__.py", line 174, in <module>
    main()
  File "/content/piper/src/python/piper_train/__main__.py", line 151, in main
    trainer.fit(model)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 1283, in _run_train
    self.fit_loop.run()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/loop.py", line 201, in run
    self.on_advance_end()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/fit_loop.py", line 299, in on_advance_end
    self.trainer._call_callback_hooks("on_train_epoch_end")
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 1597, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 312, in on_train_epoch_end
    self._save_last_checkpoint(trainer, monitor_candidates)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 653, in _save_last_checkpoint
    self._save_checkpoint(trainer, filepath)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 387, in _save_checkpoint
    trainer.save_checkpoint(filepath, self.save_weights_only)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 2427, in save_checkpoint
    self._checkpoint_connector.save_checkpoint(filepath, weights_only=weights_only, storage_options=storage_options)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 459, in save_checkpoint
    self.trainer.strategy.save_checkpoint(_checkpoint, filepath, storage_options=storage_options)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/strategies/strategy.py", line 446, in save_checkpoint
    self.checkpoint_io.save_checkpoint(checkpoint, filepath, storage_options=storage_options)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/plugins/io/torch_plugin.py", line 54, in save_checkpoint
    atomic_save(checkpoint, path)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/cloud_io.py", line 67, in atomic_save
    with fsspec.open(filepath, "wb") as f:
  File "/usr/local/lib/python3.10/dist-packages/fsspec/core.py", line 121, in __exit__
    self.close()
  File "/usr/local/lib/python3.10/dist-packages/fsspec/core.py", line 141, in close
    f.close()
  File "/usr/local/lib/python3.10/dist-packages/fsspec/implementations/local.py", line 400, in close
    return self.f.close()
OSError: [Errno 107] Transport endpoint is not connected

**Comment by MooTheCow** [comment]
Plus when I ran the Exporter notebook I got this error, and it failed to make the compressed model to download:  

Downloading model and his config...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/piper/src/python/piper_train/export_onnx.py", line 109, in <module>
    main()
  File "/content/piper/src/python/piper_train/export_onnx.py", line 42, in main
    model = VitsModel.load_from_checkpoint(args.checkpoint, dataset=None)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/core/saving.py", line 137, in load_from_checkpoint
    return _load_from_checkpoint(
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/core/saving.py", line 184, in _load_from_checkpoint
    checkpoint = pl_load(checkpoint_path, map_location=map_location)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/cloud_io.py", line 47, in load
    return torch.load(f, map_location=map_location)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 243, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
Compressing...
Done!

**Comment by MooTheCow** [comment]
Thanks for your answer.

I didn't know about the Google Drive version history.  Having to download it and then upload it again seemed to be the only option to revert to an older version.  But then I was able to run Exporter and get the model.  Thanks.

So it seems the best solution is to save multiple checkpoints to separate files, rather than use "Save Latest Model"?  I wasn't sure what values to use to make it a sensible number of checkpoints to manage. ie. so it doesn't save every single iteration.

For a 100 wav file finetune on an existing model, what is the best setting here?  Ideally saving a checkpoint every 15 mins or so. 

- How many epochs to save training checkpoints:  5
- Interval to save best k models: 1     ???  
- Save Latest Model : Unchecked

**Comment by MooTheCow** [comment]
Disregard my last questions.  I tried it with save_last off and it very quickly filled up my gdrive quota and it was a hassle keeping it running by deleting old files as they appeared.  So I'll continue to use the save_last method in future!

**Comment by rmcpantoja** [comment]
Hi,
The notebook's instructions are very clear, including removing checkpoints that are stored in the trash when you decide to save a model every x epochs without saving last. For 100 audios, I recommend the saving interval to 20 epochs instead of 5, to control the time in which they are stored.
I recommend check save last and set num_ckpt to 0 for larger datasets (>200 audios) so that the trainer is able to update the complete model instead of a corrupt one and in more time.
