### ISSUE TITLE
KeyError: 'phoneme_ids', when I try to test a checkpoint model.

### ISSUE THREAD

**Issue by jereskuta** [rhasspy/piper#315]
I've started fine tuning the lessac medium voice and I'm about 60 epochs deep. I followed the training guide and downloaded the test_en-us.jsonl file and used the command 
`cat test_en-us.jsonl | \
    python3 -m piper_train.infer \
        --sample-rate 22050 \
        --checkpoint /path/to/training_dir/lightning_logs/version_6/checkpoints/*.ckpt \
        --output-dir /path/to/training_dir/output"
`
With the command I get the following error:
`DEBUG:fsspec.local:open file: /home/jereskuta/piper/my-training/lightning_logs/version_6/checkpoints/epoch=2228-step=1358740.ckpt
DEBUG:vits.lightning:No dataset to load
Removing weight norm...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jereskuta/piper/src/python/piper_train/infer.py", line 84, in <module>
    main()
  File "/home/jereskuta/piper/src/python/piper_train/infer.py", line 52, in main
    phoneme_ids = utt["phoneme_ids"]
KeyError: 'phoneme_ids'`

So its not finding the dataset, apparently. Could it be, because the training is still running? 

I looked inside the checkpoint and it seems to have the data as it should.

**Comment by jereskuta** [comment]
Got it to work with help from Thorsten's guide. The training.md guide didn't specify you need to use the datasets in the /etc/test_sentences directory.

**Comment by MelleNi** [comment]
How exactly did you get it to work? I can't find this guide

**Comment by jereskuta** [comment]
Thorsten-Voice explains the process in his video: https://youtu.be/b_we_jma220?si=a0hOyEHlRjyVB2Ki&t=1177
So the included test files are located at ~/piper/etc/test_sentences
How I got it to work:
`cd ~/piper/etc/test_sentences

cat test_en-us.jsonl | \
    python3 -m piper_train.infer \
        --sample-rate 22050 \
        --checkpoint /path/to/training_dir/lightning_logs/version_0/checkpoints/*.ckpt \
        --output-dir /path/to/training_dir/output"`

also make sure you are in the (.venv)
