### ISSUE TITLE
training new speech problem

### ISSUE THREAD

**Issue by eix128** [rhasspy/piper#387]
The first command successfully works 
 python3 -m piper_train.preprocess --language tr --input-dir /mnt/f/Files/Works/JavaTTS/SoundWorks/piperTrain --output-dir  /
mnt/f/Files/Works/JavaTTS/SoundWorks/OutZeki --dataset-format ljspeech --sample-rate 44100

But second command on training :
python3 -m piper_train --dataset-dir /mnt/f/Files/Works/JavaTTS/SoundWorks/OutZeki --accelerator 'gpu' --devices 1 --batch-s
ize 32 --validation-split 0.2 --num-test-examples 2 --max_epochs 10000 --checkpoint-epochs 1 --precision 32

Gives error:
pytorch_lightning.utilities.exceptions.MisconfigurationException: We could not infer the batch_size from the batch. Either simplify its structure or provide the batch_size as `self.log(..., batch_size=batch_size)`.

Batch size? i already set it on command.
My detailed error:

(.venv) eix128@DESKTOP-IT5F0UV:~/piper/src/python$ python3 -m piper_train.preprocess --language tr --input-dir /mnt/f/Files/Works/JavaTTS/SoundWorks/piperTrain --output-dir  /
mnt/f/Files/Works/JavaTTS/SoundWorks/OutZeki --dataset-format ljspeech --sample-rate 44100
INFO:preprocess:Single speaker dataset
INFO:preprocess:Wrote dataset config
INFO:preprocess:Processing 75 utterance(s) with 16 worker(s)
(.venv) eix128@DESKTOP-IT5F0UV:~/piper/src/python$ python3 -m piper_train --dataset-dir /mnt/f/Files/Works/JavaTTS/SoundWorks/OutZeki --accelerator 'gpu' --devices 1 --batch-s
ize 32 --validation-split 0.2 --num-test-examples 2 --max_epochs 10000 --checkpoint-epochs 1 --precision 32
DEBUG:piper_train:Namespace(dataset_dir='/mnt/f/Files/Works/JavaTTS/SoundWorks/OutZeki', checkpoint_epochs=1, quality='medium', resume_from_single_speaker_checkpoint=None, logger=True, checkpoint_callback=None, enable_checkpointing=True, default_root_dir=None, gradient_clip_val=None, gradient_clip_algorithm=None, process_position=0, num_nodes=1, num_processes=None, devices='1', gpus=None, auto_select_gpus=False, tpu_cores=None, ipus=None, log_gpu_memory=None, progress_bar_refresh_rate=None, enable_progress_bar=True, overfit_batches=0.0, track_grad_norm=-1, check_val_every_n_epoch=1, fast_dev_run=False, accumulate_grad_batches=None, max_epochs=10000, min_epochs=None, max_steps=-1, min_steps=None, max_time=None, limit_train_batches=None, limit_val_batches=None, limit_test_batches=None, limit_predict_batches=None, val_check_interval=None, flush_logs_every_n_steps=None, log_every_n_steps=50, accelerator='gpu', strategy=None, sync_batchnorm=False, precision=32, enable_model_summary=True, weights_summary='top', weights_save_path=None, num_sanity_val_steps=2, resume_from_checkpoint=None, profiler=None, benchmark=None, deterministic=False, reload_dataloaders_every_n_epochs=0, auto_lr_find=False, replace_sampler_ddp=True, detect_anomaly=False, auto_scale_batch_size=False, prepare_data_per_node=None, plugins=None, amp_backend='native', amp_level=None, move_metrics_to_cpu=False, multiple_trainloader_mode='max_size_cycle', stochastic_weight_avg=False, terminate_on_nan=None, batch_size=32, validation_split=0.2, num_test_examples=2, max_phoneme_ids=None, hidden_channels=192, inter_channels=192, filter_channels=768, n_layers=6, n_heads=2, seed=1234)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
DEBUG:piper_train:Checkpoints will be saved every 1 epoch(s)
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmpisk8_i64
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmpisk8_i64/_remote_module_non_scriptable.py
DEBUG:vits.dataset:Loading dataset: /mnt/f/Files/Works/JavaTTS/SoundWorks/OutZeki/dataset.jsonl
Missing logger folder: /mnt/f/Files/Works/JavaTTS/SoundWorks/OutZeki/lightning_logs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
DEBUG:fsspec.local:open file: /mnt/f/Files/Works/JavaTTS/SoundWorks/OutZeki/lightning_logs/version_0/hparams.yaml
/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:240: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/kadirbasol/piper/src/python/piper_train/__main__.py", line 147, in <module>
    main()
  File "/home/kadirbasol/piper/src/python/piper_train/__main__.py", line 124, in main
    trainer.fit(model)
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 771, in fit
    self._call_and_handle_interrupt(
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 724, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 812, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1237, in _run
    results = self._run_stage()
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1324, in _run_stage
    return self._run_train()
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1346, in _run_train
    self._run_sanity_check()
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1414, in _run_sanity_check
    val_loop.run()
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 153, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 127, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 222, in _evaluation_step
    output = self.trainer._call_strategy_hook("validation_step", *kwargs.values())
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1766, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 344, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/kadirbasol/piper/src/python/piper_train/vits/lightning.py", line 283, in validation_step
    val_loss = self.training_step_g(batch) + self.training_step_d(batch)
  File "/home/kadirbasol/piper/src/python/piper_train/vits/lightning.py", line 261, in training_step_g
    self.log("loss_gen_all", loss_gen_all)
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/core/lightning.py", line 417, in log
    results.log(
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py", line 493, in log
    batch_size = self._extract_batch_size(self[key], batch_size, meta)
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py", line 428, in _extract_batch_size
    batch_size = extract_batch_size(self.batch)
  File "/home/kadirbasol/piper/src/python/.venv/lib/python3.10/site-packages/pytorch_lightning/utilities/data.py", line 81, in extract_batch_size
    raise MisconfigurationException(error_msg)
pytorch_lightning.utilities.exceptions.MisconfigurationException: We could not infer the batch_size from the batch. Either simplify its structure or provide the batch_size as `self.log(..., batch_size=batch_size)`.

**Comment by daviddudas99** [comment]
I had same problem and was able to fix it. 

I updated requirements in src/python/...:
```
cython>=0.29.0,<1
piper-phonemize~=1.1.0
librosa>=0.9.2,<1
numpy>=1.19.0
onnxruntime>=1.11.0
pytorch-lightning~=1.7.0
torch>=1.11.0,<2
```

And run the code with parameter `--quality medium`. It is possible that just adding `--quality medium` without updating requirements might work. 

This is working (not using docker but conda env):
`python -m piper_train   --dataset-dir ./training_dir   --accelerator 'gpu'   --devices 1   --batch-size 32   --validation-split 0.00   --num-test-examples 0   --max_epochs 10000   --checkpoint-epochs 1   --precision 32   --quality medium`
