### ISSUE TITLE
error when preparing files for training

### ISSUE THREAD

**Issue by Ukias** [rhasspy/piper#409]
I encounter a problem when trying to generate the `config.json` and the `dataset.jsonl`. Stacktrace:
```
Traceback (most recent call last):
  File "/home/stefan/anaconda3/envs/tortoise/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/stefan/anaconda3/envs/tortoise/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/stefan/Documents/spracherzeugung_aus_pdf/piper/src/python/piper_train/preprocess.py", line 502, in <module>
    main()
  File "/home/stefan/Documents/spracherzeugung_aus_pdf/piper/src/python/piper_train/preprocess.py", line 225, in main
    for utt_batch in batched(
  File "/home/stefan/Documents/spracherzeugung_aus_pdf/piper/src/python/piper_train/preprocess.py", line 491, in batched
    raise ValueError("n must be at least one")
ValueError: n must be at least one
```

Can you help me out to find the error?

**Comment by Dabsterr** [comment]
same issue. others noted that combined training data needs to be >5 mins. but mine is around 20+ with the same issue.

**Comment by coffeecodeconverter** [comment]
solutions here:
https://github.com/rhasspy/piper/issues/297
