### ISSUE TITLE
Issue running on Raspberry pi 5

### ISSUE THREAD

**Issue by wyrmwood9** [rhasspy/piper#432]
While following Thorsten's tutorial for running a local Piper TTS server with Python on Linux
https://www.youtube.com/watch?v=pLR5AsbCMHs

I encounter the error when trying to run the http server
`
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/mm/piper/src/python_run/piper/http_server.py", line 127, in <module>
    main()
  File "/home/mm/piper/src/python_run/piper/http_server.py", line 93, in main
    voice = PiperVoice.load(args.model, config_path=args.config, use_cuda=args.cuda)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mm/piper/src/python_run/piper/voice.py", line 35, in load
    config_dict = json.load(config_file)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`
This is on a Raspberry Pi 5 (4GB) running Pi OS Bookworm 12.2.0 (uname -a
Linux raspberrypi 6.1.0-rpi8-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64 GNU/Linux)

any ideas?

**Comment by ausgomez** [comment]
I am getting exactly the same error following that video, did you ever figure this out?

**Comment by ausgomez** [comment]
actually I found the issue! just dont include the extension at the end of the model's file like for example:
`python3 -m piper.http_server --model en_US-danny-low`
