### ISSUE TITLE
AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'

### ISSUE THREAD

**Issue by ZYROS-OFFICIEL** [rhasspy/piper#436]
` python3 -m piper_train \
>     --dataset-dir ~/piper/my-training \
>     --accelerator 'gpu' \
>     --devices 1 \
>     --batch-size 32 \
>     --validation-split 0.0 \
>     --num-test-examples 0 \
>     --max_epochs 6000 \
--resume>     --resume_from_checkpoint ~/piper/epoch=2164-step=1355540.ckpt \
>     --checkpoint-epochs 1 \
>     --precision 32
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/anas/piper/src/python/piper_train/__main__.py", line 147, in <module>
    main()
  File "/home/anas/piper/src/python/piper_train/__main__.py", line 37, in main
    Trainer.add_argparse_args(parser)
AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'`I have this problem and i don't know how to solve it ,i don't have an nvidia gpu though.

**Comment by eusthace811** [comment]
Did you find how to fix this?

**Comment by synesthesiam** [comment]
I'm guessing PyTorch Lightning broke their API again?

**Comment by ZYROS-OFFICIEL** [comment]
> Did you find how to fix this?

If i remember right i replaced the accelator'cpu' instead of gpu beacause it doesn't support amd gpu

**Comment by mehdihosseinimoghadam** [comment]
The method removed in 2.0, so the AttributeError is expected.

**Comment by ZYROS-OFFICIEL** [comment]
I'm sorry ,i'm not sure to understand what do you mean.

**Comment by yilmazay74** [comment]
So, if pytorch_lightning api has changed and some things are broken, should not that be fixed (replaced by its alternative) by piper? These kind of issues really damage piper's reliability.

**Comment by nmstoker** [comment]
YMMV but I found that switching to an earlier version worked (despite pip warning me that there were issues with the incompatible versions). That fits with Mehdi's comment above about the method being removed in 2.0.

I just did this: `pip install pytorch-lightning==1.9.5` and then ran training.

Training seems fine - I did get a lot of warning messages in the terminal but none of them seemed fatal and I've confirmed that the training is starting to have a positive effect (ie it does sound increasingly like the training dataset 🙂 )

**Comment by ZYROS-OFFICIEL** [comment]
> YMMV but I found that switching to an earlier version worked (despite pip warning me that there were issues with the incompatible versions). That fits with Mehdi's comment above about the method being removed in 2.0.
> 
> 
> 
> I just did this: `pip install pytorch-lightning==1.9.5` and then ran training.
> 
> 
> 
> Training seems fine - I did get a lot of warning messages in the terminal but none of them seemed fatal and I've confirmed that the training is starting to have a positive effect (ie it does sound increasingly like the training dataset 🙂 )

Yeah... It needs large amount of training to start saying something that has sense.
