### ISSUE TITLE
Is the Chinese language code currently using cmn or zh_cN?

### ISSUE THREAD

**Issue by qt06** [rhasspy/piper#505]
Is the Chinese language code currently using cmn or zh_cN?

**Comment by ken107** [comment]
You can see here they're all 2 letter ISO 639-1 codes https://huggingface.co/rhasspy/piper-voices/tree/v1.0.0
And please ask questions in the Discussions section instead

**Comment by lixikun** [comment]
I want to train a new single speaker model on aishell dataset , but when I set the language to zh, the preprocess script gets the following err, but when I set cmn, the proprocess script works. Is it wrong or right?

ERROR:preprocess:Failed to process utterance: Utterance(text='培训费每人一千二百元', audio_path=PosixPath('/workspace/dataset/wavs/BAC009S0174W0461.wav'), speaker=None, speaker_id=None, phonemes=None, phoneme_ids=None, audio_norm_path=None, audio_spec_path=None, missing_phonemes=Counter())
Traceback (most recent call last):
  File "/workspace/piper/src/python/piper_train/preprocess.py", line 302, in phonemize_batch_espeak
    all_phonemes = phonemize_espeak(casing(utt.text), args.language)
  File "/opt/conda/lib/python3.10/site-packages/piper_phonemize/__init__.py", line 38, in phonemize_espeak
    return _phonemize_espeak(text, voice, str(data_path))
RuntimeError: Failed to set eSpeak-ng voice
