### ISSUE TITLE
it_IT-paola-medium not downloadable

### ISSUE THREAD

**Issue by IoSonoAndreaZ** [rhasspy/piper#514]
This voice is not downloadable and working

**Comment by IoSonoAndreaZ** [comment]
link not working: https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/lessac/medium/it_IT-paola-medium.onnx
same for the json

**Comment by TikoTako** [comment]
> link not working: https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/lessac/medium/it_IT-paola-medium.onnx same for the json
> v1.0.0
> en/en_US/
there is no paola in v1.0.0 only riccardo and is italian not english
https://huggingface.co/rhasspy/piper-voices/resolve/main/it/it_IT/paola/medium/it_IT-paola-medium.onnx?download=true
https://huggingface.co/rhasspy/piper-voices/resolve/main/it/it_IT/paola/medium/it_IT-paola-medium.onnx.json?download=true

**Comment by synesthesiam** [comment]
I just forgot to move the git tag. This has been fixed now. Thanks for letting me know :+1:

**Comment by IoSonoAndreaZ** [comment]
> I just forgot to move the git tag. This has been fixed now. Thanks for letting me know 👍

still, i can't download it:
wyoming_piper.download.VoiceNotFoundError: it_IT-paola-medium


manually downloading and putting in the same directory as riccardo:

```
root@krogberry:/opt/piper-data# ll
totale 89512
-rw-r--r-- 1 root krog     7099  2 giu 16.14 it_IT-paola-medium.json
-rw-r--r-- 1 root krog 63511038  2 giu 16.14 it_IT-paola-medium.onnx
-rw-r--r-- 1 root root 28130791 28 mag 13.36 it_IT-riccardo-x_low.onnx
-rw-r--r-- 1 root root     4161 28 mag 13.36 it_IT-riccardo-x_low.onnx.json
```

but still, Piper can't find it:

```

Traceback (most recent call last):

  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/__main__.py", line 223, in <module>

    run()

  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/__main__.py", line 218, in run

    asyncio.run(main())

  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run

    return loop.run_until_complete(main)

  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete

    return future.result()

  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/__main__.py", line 138, in main

    custom_voice_path, custom_config_path = find_voice(

  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/download.py", line 183, in find_voice

    raise VoiceNotFoundError(name)

wyoming_piper.download.VoiceNotFoundError: it_IT-paola-medium
```

**Comment by Riverxik** [comment]
@IoSonoAndreaZ, I assume it can't find config file for voice. By default it finding like: <modelfileWithExtension>.json
> wyoming_piper.download.VoiceNotFoundError: it_IT-paola-medium
> it_IT-paola-medium.json

Look at your it_IT-riccardo-x_low voice files.
Try to rename it.
You should have this names in folder:
- it_IT-paola-medium.onnx.json - config
- it_IT-paola-medium.onnx - model

**Comment by IoSonoAndreaZ** [comment]
> * it_IT-paola-medium.onnx.json

```
INFO:__main__:Ready

ERROR:asyncio:Task exception was never retrieved

future: <Task finished name='wyoming event handler' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.9/dist-packages/wyoming/server.py:31> exception=VoiceNotFoundError('paola')>

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/dist-packages/wyoming/server.py", line 41, in run

    if not (await self.handle_event(event)):

  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/handler.py", line 53, in handle_event

    raise err

  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/handler.py", line 48, in handle_event

    return await self._handle_event(event)

  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/handler.py", line 83, in _handle_event

    piper_proc = await self.process_manager.get_process(voice_name=voice_name)

  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/process.py", line 114, in get_process

    ensure_voice_exists(

  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/download.py", line 77, in ensure_voice_exists

    find_voice(name, data_dirs)

  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/download.py", line 183, in find_voice

    raise VoiceNotFoundError(name)

wyoming_piper.download.VoiceNotFoundError: paola
```

```
-rw-r--r-- 1 root krog 63511038  2 giu 16.14 it_IT-paola-medium.onnx
-rw-r--r-- 1 root krog     7099  2 giu 16.14 it_IT-paola-medium.onnx.json
-rw-r--r-- 1 root root 28130791 28 mag 13.36 it_IT-riccardo-x_low.onnx
-rw-r--r-- 1 root root     4161 28 mag 13.36 it_IT-riccardo-x_low.onnx.json
```

**Comment by TikoTako** [comment]
you are using the local 'voices.json' of wyoming_piper that is 4 months old instead of the remote one in https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ that was updated 4 days ago

**Comment by IoSonoAndreaZ** [comment]
i'm using rhasspy/wyoming-piper docker image

**Comment by TikoTako** [comment]
i never used docker but i guess it run __main__.py, try to run it with `--update-voices`

**Comment by IoSonoAndreaZ** [comment]
> i never used docker but i guess it run `__main__.py`, try to run it with `--update-voices`

it worked, thank you!
