### ISSUE TITLE
trying to train and im getting a not enough columns error

### ISSUE THREAD

**Issue by ConanWolf46** [rhasspy/piper#516]
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/NAME/piper/src/python/piper_train/preprocess.py", line 502, in <module>
    main()
  File "/home/NAME/piper/src/python/piper_train/preprocess.py", line 143, in main
    for utt in make_dataset(args):
  File "/home/NAME/piper/src/python/piper_train/preprocess.py", line 423, in ljspeech_dataset
    assert len(row) >= 2, "Not enough columns"
AssertionError: Not enough columns
```

my training command:
```
python3 -m piper_train.preprocess --language en --input-dir ~/newvoice/Me   --dataset
-format ljspeech   --single-speaker   --sample-rate 22050 --output-dir ~/newvoice/Me/output
```

**Comment by ConanWolf46** [comment]
ahh yes please dont use the ``` marks properly

**Comment by ConanWolf46** [comment]
and the format of my dataset is in a .csv file being columns A the path to the audio, and columns B the content of the audio

**Comment by ConanWolf46** [comment]
ok i fixed it by setting everything to 1 column and adding a | between everything, but thats a really janky way of doing it, at that point why not just allow a standard file to be read from?
