### ISSUE TITLE
Raspberry Pi Python Error.

### ISSUE THREAD

**Issue by TLsolutionstg** [rhasspy/piper#586]
I am writing a python program on raspberry pi using piper tts for text to speech. my code segment is (message is pulled from an outside str variable):
model = "/home/loomi/Desktop/FlaskTest/en_en_GB_aru_medium_en_GB-aru-medium.onnx"
voice_config = "/home/loomi/Desktop/FlaskTest/en_en_GB_aru_medium_en_GB-aru-medium.onnx.json"
voice = PiperVoice(model,voice_config)
wav_file = wave.open("message1.wav","w")
audio = voice.synthesize(message, wav_file)

The error I am getting is:
  File "/home/loomi/Desktop/FlaskTest/app.py", line 81, in message_setup
    audio = voice.synthesize(message, wav_file)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/loomi/Desktop/FlaskTest/venv/lib/python3.11/site-packages/piper/voice.py", line 91, in synthesize
    wav_file.setframerate(self.config.sample_rate)
                          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'sample_rate'
Exception ignored in: <function Wave_write.__del__ at 0x7fff3d1d6660>
Traceback (most recent call last):
  File "/usr/lib/python3.11/wave.py", line 447, in __del__
    self.close()
  File "/usr/lib/python3.11/wave.py", line 565, in close
    self._ensure_header_written(0)
  File "/usr/lib/python3.11/wave.py", line 583, in _ensure_header_written
    raise Error('# channels not specified')
wave.Error: # channels not specified

Is this an issue with my code, or an issue with the repository?

**Comment by TLsolutionstg** [comment]
> Hi @TLsolutionstg , try this:
> 
> ```python
> model = "/home/loomi/Desktop/FlaskTest/en_en_GB_aru_medium_en_GB-aru-medium.onnx"
> voice_config = "/home/loomi/Desktop/FlaskTest/en_en_GB_aru_medium_en_GB-aru-medium.onnx.json"
> voice = PiperVoice.load(model,voice_config)
> wav_file = wave.open("message1.wav","w")
> audio = voice.synthesize(message, wav_file)
> ```
> 
> The PiperVoice object is created with the load method. Hope this works for you.

If I use this code, I get an onnx runtime error. is there maybe a dependency that does not come installed on the pip install piper-tts? Here is the error:
model = "/home/loomi/Desktop/FlaskTest/en_en_GB_aru_medium_en_GB-aru-medium.onnx"
voice_config = "/home/loomi/Desktop/FlaskTest/en_en_GB_aru_medium_en_GB-aru-medium.onnx.json"
voice = PiperVoice.load(model,voice_config)
wav_file = wave.open("message1.wav","w")
audio = voice.synthesize(message, wav_file)
