### ISSUE TITLE
Vietnamese phonemes

### ISSUE THREAD

**Issue by sultanovazamat** [rhasspy/piper#60]
Hi, thanks for the great library!

I am trying to run inference using vietnamese models, but this is what I get for both of the available models:

`echo 'Trăm năm trong cõi người ta, chữ tài chữ mệnh khéo là ghét nhau.' | scripts/piper --model voices/vi/vi-25hours-single-low.onnx --output_file welcome.wav
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/piper/piper/src/python_run/piper/__main__.py", line 74, in <module>
    main()
  File "/workspace/piper/piper/src/python_run/piper/__main__.py", line 63, in main
    wav_bytes = synthesize(text)
  File "/workspace/piper/piper/src/python_run/piper/__init__.py", line 72, in synthesize
    phoneme_ids.extend(self.config.phoneme_id_map[phoneme])
KeyError: '1'`

Do you have any ideas why is this happening? Thanks.

**Comment by trunglebka** [comment]
Vietnamese here, Piper Vietnamese voice is not good. I think the problem is poor dataset and phoneme set does not fit Vietnamese

**Comment by synesthesiam** [comment]
@sultanovazamat A fix is coming soon for this! As @trunglebka there are problems with the Vietnamese phonemes in Piper. I don't know how good espeak-ng's phonemes are (where Piper gets them), but there was a bug that was discarding some phonemes during training -- specifically the tones that Vietnamese would rely on.
