### ISSUE TITLE
Exporting error

### ISSUE THREAD

**Issue by OMVMMG** [rhasspy/piper#634]
I'm getting this error when exporting: 

ERROR:__main__:export_audio
Traceback (most recent call last):
  File "/home/test/piper-recording-studio/export_dataset/__main__.py", line 107, in __call__
    audio_16khz_bytes = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-i', 'output/en-GB/4000000001_4000000300_CustomerService/4000000006.webm', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '16000', 'pipe:']' returned non-zero exit status 1.

Any ideas what is going on?
Thank you for your help.

**Comment by thelabcat** [comment]
English version: "I tried to run the program FFmpeg to do a job for me, but it failed, probably because I tried to call it with too few arguments or an incorrect option."

It's unlikely, but it is a low hanging fruit; are you sure FFmpeg is installed and on path?
